version: "3.3"

services:
  zabbix:
    image: zabbix/zabbix-server-mysql
    env_file:
      - docker-compose.env
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

  zabbix-fe:
    image: zabbix/zabbix-web-nginx-mysql
    environment:
      VIRTUAL_HOST: zabbix.deverello.de
      LETSENCRYPT_HOST: zabbix.deverello.de
      LETSENCRYPT_EMAIL: johannes.hinkov@gmail.com
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network
      - auto-proxy

  zabbix-db:
    image: mariadb
    env_file:
      - docker-compose.env
    networks:
      - zabbix-network
    volumes:
      - zabbix-db:/var/lib/mysql

  zabbix-agent:
    image: zabbix/zabbix-agent2
    env_file:
      - docker-compose.env
    privileged: true
    networks:
      - zabbix-network

networks:
  zabbix-network:
  auto-proxy:
    external: true

volumes:
  zabbix-db: